// src/react/BlogList.tsx
/**
 * React BlogList Component
 * Displays a list of articles with pagination
 */

import React, { useEffect, useRef } from 'react';
import { ContentGrowthWidget } from '../widget/widget.js';
import type { BlogListProps } from '../types/index.js';

export interface ReactBlogListProps extends Omit<BlogListProps, 'class'> {
  className?: string;
}

export const BlogList: React.FC<ReactBlogListProps> = ({
  apiKey,
  baseUrl,
  layout = 'cards',
  displayMode = 'comfortable',
  theme = 'light',
  pageSize = 12,
  tags = [],
  category,
  showPagination = true,
  className = ''
}) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const widgetRef = useRef<ContentGrowthWidget | null>(null);

  useEffect(() => {
    if (!containerRef.current) return;

    // Initialize widget
    widgetRef.current = new ContentGrowthWidget(containerRef.current, {
      apiKey,
      baseUrl,
      layoutMode: layout,
      displayMode,
      theme,
      pageSize,
      tags: Array.isArray(tags) ? tags : [],
      category,
      mode: 'list'
    });

    // Cleanup on unmount
    return () => {
      if (widgetRef.current && containerRef.current) {
        containerRef.current.innerHTML = '';
      }
    };
  }, [apiKey, baseUrl, layout, displayMode, theme, pageSize, tags, category]);

  return (
    <div
      ref={containerRef}
      className={`cg-blog-list cg-layout-${layout} cg-display-${displayMode} cg-theme-${theme} ${className}`}
      data-cg-widget="list"
    />
  );
};

export default BlogList;

// src/vue/BlogList.vue
<template>
  <div
    ref="containerRef"
    :class="`cg-blog-list cg-layout-${layout} cg-display-${displayMode} cg-theme-${theme} ${className}`"
    data-cg-widget="list"
  />
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { ContentGrowthWidget } from '../widget/widget.js';
import type { BlogListProps } from '../types/index.js';

export interface VueBlogListProps extends Omit<BlogListProps, 'class'> {
  className?: string;
}

const props = withDefaults(defineProps<VueBlogListProps>(), {
  layout: 'cards',
  displayMode: 'comfortable',
  theme: 'light',
  pageSize: 12,
  tags: () => [],
  showPagination: true,
  className: ''
});

const containerRef = ref<HTMLDivElement | null>(null);
let widget: ContentGrowthWidget | null = null;

const initWidget = () => {
  if (!containerRef.value) return;

  // Clean up existing widget
  if (widget) {
    containerRef.value.innerHTML = '';
  }

  // Initialize new widget
  widget = new ContentGrowthWidget(containerRef.value, {
    apiKey: props.apiKey,
    baseUrl: props.baseUrl,
    layoutMode: props.layout,
    displayMode: props.displayMode,
    theme: props.theme,
    pageSize: props.pageSize,
    tags: Array.isArray(props.tags) ? props.tags : [],
    category: props.category,
    mode: 'list'
  });
};

onMounted(() => {
  initWidget();
});

onUnmounted(() => {
  if (widget && containerRef.value) {
    containerRef.value.innerHTML = '';
  }
});

// Re-initialize widget when props change
watch(
  () => [props.apiKey, props.baseUrl, props.layout, props.displayMode, props.theme, props.pageSize, props.tags, props.category],
  () => {
    initWidget();
  }
);
</script>
